---
title: "Scratch R Code"
author: "Matthew Muller"
output:
  pdf_document:
    toc: true
    toc_float: true
---

# PRESS451 Correlation Analysis
```{r, echo=FALSE}
# Load the data
dat <- read.csv('data/clean/pace/features.csv', row.names=1)

ComplexHeatmap::Heatmap(
    cor(dat, method = 'spearman'),
    name = 'Rho',
    col = circlize::colorRamp2(c(-1, 0, 1), c("blue", "white", "red")),
    show_row_names = TRUE,
    show_column_names = FALSE,
    row_names_gp = grid::gpar(fontsize = 4)
    )
```


# Look at the bleeding
```{r, echo=FALSE}
dat <- read.csv('data/metadata_9_20220422.csv', row.names=1)
colnames(dat)

with(dat, table(comp_bleeding__strmajorbleed_v_nobleed))
```

```{r}
library(ggplot2)
p <- 'shared/20240312_reviewer_request/fig3/fig3e_pace_derivation_scores.csv'
p2 <- '/Users/muller/Library/CloudStorage/GoogleDrive-mm12865@nyu.edu/My Drive/RugglesLab/projects/platelet-activity/output/pace_scores_press_01.csv'
p3 <- '/Users/muller/Library/CloudStorage/GoogleDrive-mm12865@nyu.edu/My Drive/RugglesLab/projects/platelet-activity/output/pace_predictions.csv'
x <- read.csv(p, row.names=1)
x2 <- read.csv(p2, row.names=1)
x3 <- read.csv(p3, row.names=1)
x <- rbind(x, x2)
ggplot(x3, aes(x = factor(label), y = score)) +
    geom_boxplot()


# let's try another folder
p4 <- '/Users/muller/Library/CloudStorage/GoogleDrive-mm12865@nyu.edu/My Drive/RugglesLab/projects/platelet-activity/output/pace_press_scoring_tiles__run_4/pace_press_metadata_with_scores_and_tiles.csv'
x4 <- read.csv(p4, row.names=1)
colnames(x4)
ggplot(x4, aes(x = factor(labels), y = scores)) +
    geom_boxplot()
```